apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: spout
  name: spout
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spout
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: spout
    spec:
      containers:
      - env:
        - name: PORT
          value: "8082"
        - name: URL
          value: http://prometheus:9090
        image: spout
        imagePullPolicy: ""
        name: spout
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
