apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
  
    matchLabels:
      io.kompose.service: api-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: api-gateway
    spec:
      containers:
      - env:
        - name: MAX_FILE_SIZE
          value: "10000"
        - name: PORT
          value: "8080"
        - name: RESPONSE_TIMEOUT
          value: "2000"
        - name: URL
          value: http://myapp:8081
        image: api_gateway
        imagePullPolicy: Never
        name: api-gateway
        ports:
        - containerPort: 30036
        resources: {}
        volumeMounts:
        - mountPath: /api_gateway/storage
          name: api-gateway-claim0
        - mountPath: /home/nino/Scrivania/homework_DSB-kubernetes/homework_DSB/storage
         
          name: testclaim
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: api-gateway-claim0
        persistentVolumeClaim:
          claimName: api-gateway-claim0
      - name: testclaim
        persistentVolumeClaim:
          claimName: testclaim
status: {}
