apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: application
  name: application
spec:
  containers:
  - env:
    - name: ACCESS_KEY
      value: mauro
    - name: DB_PASSWORD
      value: mauro
    - name: DB_URL
      value: jdbc:mysql://dockermysql:3306/homework_db
    - name: DB_USERNAME
      value: mauro
    - name: MINIO_URL
      value: http://dockerminio:9000
    - name: PORT
      value: "8081"
    - name: SECRET_KEY
      value: maurolabruna
    image: myapp
    name: myapp
    ports:
    - containerPort: 8081
    resources: {}
    volumeMounts:
    - mountPath: /data/
      name: application-claim0
  restartPolicy: OnFailure
  volumes:
  - name: application-claim0
    persistentVolumeClaim:
      claimName: application-claim0
status: {}
