apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - env:
        - name: ACCESS_KEY
          value: mauro
        - name: DB_PASSWORD
          value: mauro
        - name: DB_URL
          value: jdbc:mysql://mysql-headless-service:3306/homework_db
        - name: DB_USERNAME
          value: mauro
        - name: MINIO_URL
          value: http://minio:9000
        - name: PORT
          value: "8081"
        - name: SECRET_KEY
          value: maurolabruna
        - name: MY_URL
          value: 192.168.39.156:31367 
        image: mbauro/filemanagementservice
        imagePullPolicy: IfNotPresent
        name: myapp

        workingDir: /myapp/storage/homework_DSB/files/

        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:

        - mountPath: /myapp/storage
          name: application-claim0

      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: application-claim0
        persistentVolumeClaim:

          claimName: myapp-pvc

status: {}
