apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:

  type: ClusterIP

  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: myapp
status:
  loadBalancer: {}
