apiVersion: v1
kind: Service
metadata:
  name: consumer-service
  labels:
    app: consumer
spec:

  type: NodePort


  ports:
  - name: "innerport"
    port: 8084
    targetPort: 8084

  - name: "outport"
    port: 9998
    nodePort: 30002

  selector:
    app: consumer
status:
  loadBalancer: {}
