apiVersion: v1
kind: PersistentVolume
metadata:
  name: consumer-pv
  labels:
    type: local
spec:
  storageClassName: consumer-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/storage/consumer/" 
