apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30679"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.99.104
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        image: wurstmeister/kafka
        imagePullPolicy: ""
        name: kafka
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
