apiVersion: apps/v1

kind: StatefulSet

metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
spec:

  serviceName: "minio"

  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: minio


  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: minio

        app: minio

    spec:
      containers:
      - args:
        - minio
        - server
        - ./storage
        env:
        - name: MINIO_ACCESS_KEY
          value: mauro
        - name: MINIO_SECRET_KEY
          value: maurolabruna
        image: minio/minio
        imagePullPolicy: ""
        name: minio
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /minio/storage
          name: minio-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: minio-claim0
        persistentVolumeClaim:
          claimName: minio-claim0

status:
  replicas: 3

