apiVersion: v1
kind: Service
metadata:
  name: minio-headless-service
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: minio
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000

