apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (HEAD)
  creationTimestamp: null

  name: minio-service
spec:
  type: LoadBalancer

  ports:
  - name: "9000"
    port: 8081
    targetPort: 9000
  selector:
    app: minio

status:
  loadBalancer: {}
