apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  type: NodePort
  ports:
  - name: "3307"
    #port is the port exposed to the other pods
    #targetPort is the port exposed by the container
    port: 3307
    targetPort: 3306
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
