apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
 
