apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: homework_db
        - name: MYSQL_PASSWORD
          value: mauro
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_ROOT_USER
          value: root
        - name: MYSQL_USER
          value: mauro
        image: mysql
        imagePullPolicy: ""
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /db/storage
          name: mysql-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: mysql-claim0
        persistentVolumeClaim:
          claimName: mysql-claim0
status: 
  replicas: 1
