apiVersion: v1
kind: Service
metadata:
  name: prometheus-headless-service
spec:
  clusterIP: None # <-- Don't forget!!
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090

