apiVersion: v1
kind: PersistentVolume
metadata:
  name: spout-pv
  labels:
    type: local
spec:
  storageClassName: spout-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/storage/storage/spout/" 
