apiVersion: v1
kind: PersistentVolume
metadata:
  name: test
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/nino/Scrivania/homework_DSB-kubernetes/homework_DSB/storage/"
