version: '3'
services:

  application:
    container_name: myapp
    image: myapp
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    hostname: filemanagementservice
    environment:
      - DB_URL=jdbc:mysql://dockermysql:3306/homework_db
      - DB_USERNAME=nino
      - DB_PASSWORD=nino
    ports:
      - "8080:9000"
    volumes:
      - /home/mauro/tmp:/storage
    restart: on-failure:2

  db:
    container_name: dockermysql
    image: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=coppolino
      - MYSQL_DATABASE=homework_db
      - MYSQL_USER=nino
      - MYSQL_PASSWORD=nino

    ports:
      - "3307:3306"

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

    volumes:
      - /home/mauro/tmp:/storage

  api_gateway:
    container_name: apigateway
    image: api_gateway
    ports:
    - "8081:8081"
    links:
     - application
    depends_on:
      - application
    #volumes:
     # - /home/mauro/tmp:/storage
